[workspace]
resolver = "2"

members = ["dmg", "frontend", "mbc"]
default-run = "frontend"

[profile.release]
opt-level = 2
lto = "fat"
panic = "abort"
overflow-checks = false
strip = true


[profile.dev]
opt-level = 3
debug = "full"
lto = "none"
