# build with x86-64-v3 target-cpu on x86
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

# build with native target-cpu on aarch64
[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-windows-msvc]
rustflags = ["-Ctarget-cpu=native"]

[target.aarch64-pc-windows-gnu]
rustflags = ["-Ctarget-cpu=native"]